[colors]
background       = '#1e1e2e'
black            = '#181825'
blue             = '#89b4fa'
cursor           = '#f5e0dc'
cyan             = '#89dceb'
foreground       = '#cdd6f4'
green            = '#a6e3a1'
magenta          = '#cba6f7'
red              = '#f38ba8'
tabs             = '#313244'
tabs-active      = '#f5e0dc'
white            = '#f5e0dc'
yellow           = '#f9e2af'
light-black      = '#585b70'
light-blue       = '#89b4fa'
light-cyan       = '#94e2d5'
light-green      = '#a6e3a1'
light-magenta    = '#f5c2e7'
light-red        = '#f38ba8'
light-white      = '#a6adc8'
light-yellow     = '#f9e2af'
