add_newline = false

[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold red)"

[package]
disabled = true

[git_branch]
format = "[$branch](bright-black)"

[git_status]
format = "[[( $conflicted$untracked$modified$staged$renamed$deleted )](218)( $ahead_behind$stashed )](cyan)"
modified="∼"
untracked="∻"
deleted = "×"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)](bright-black)\) '
