theme = "catppuccin_mocha_custom"

[editor]
true-color = true
cursorline = true
bufferline = "multiple"
color-modes = true
auto-pairs = false
auto-format = false
completion-replace = true

[editor.lsp]
display-signature-help-docs = false
auto-signature-help = false

[editor.soft-wrap]
enable = true

[editor.statusline]
separator = "⋮"
left = ["mode", "spinner", "file-name", "file-encoding"]
center = []
right = ["diagnostics", "selections", "separator", "position", "separator", "position-percentage", "spacer"]
mode.normal = "ᚺ NORMAL"
mode.insert = "ᛯ INSERT"
mode.select = "ᛋ SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
a = ["collapse_selection", "append_mode"]
i = ["collapse_selection", "insert_mode"]
x = ["yank_main_selection_to_clipboard","delete_selection"]
d = ["delete_selection"]
y = ["yank_main_selection_to_clipboard", "collapse_selection"]
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
V = ["select_mode", "extend_to_line_bounds"]
v = ["select_mode", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
C = ["extend_to_line_end", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "delete_selection"]
C-a = ["select_all"]
tab = ["rotate_view"]
S-tab = ["rotate_view_reverse"]

[keys.select]
x = ["yank_main_selection_to_clipboard","delete_selection"]
y = ["yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
d = ["delete_selection", "collapse_selection", "normal_mode"]
p = ["replace_selections_with_clipboard", "collapse_selection", "normal_mode"]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
esc = ["normal_mode","collapse_selection", "keep_primary_selection"]
C-a = "select_all"
tab = ["indent"]
S-tab = ["unindent"]

