theme = "catppuccin_mocha"

[editor]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":write"
y = ":clipboard-yank"
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"

[keys.select]
y = ":clipboard-yank"
p = ":clipboard-paste-replace"
P = ":clipboard-paste-replace"
