theme = "catppuccin_mocha_custom"

[editor]
true-color = true
cursorline = true
bufferline = "always"
color-modes = true
completion-replace = true

[editor.lsp]
display-signature-help-docs = false
auto-signature-help = false

[editor.soft-wrap]
enable = true

[editor.statusline]
separator = "⋮"
left = ["mode", "spinner", "file-name", "file-encoding"]
center = []
right = ["diagnostics", "selections", "separator", "position", "separator", "position-percentage", "spacer"]
mode.normal = "NΘRMΛL"
mode.insert = "IΠSΞRT"
mode.select = "SΞLΞCT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
a = ["collapse_selection", "append_mode"]
i = ["collapse_selection", "insert_mode"]
x = ["yank_main_selection_to_clipboard","delete_selection"]
d = ["delete_selection"]
y = ["yank_main_selection_to_clipboard", "collapse_selection"]
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
V = ["select_mode", "extend_to_line_bounds"]
v = ["collapse_selection","select_mode"]
esc = ["collapse_selection", "keep_primary_selection"]
C = ["extend_to_line_end", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "delete_selection"]
C-a = ["select_all"]
tab = ["rotate_view"]
S-tab = ["rotate_view_reverse"]

[keys.select]
x = ["yank_main_selection_to_clipboard","delete_selection"]
y = ["yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
d = ["delete_selection", "collapse_selection", "normal_mode"]
p = ["replace_selections_with_clipboard", "collapse_selection", "normal_mode"]
P = ["replace_selections_with_clipboard", "collapse_selection", "normal_mode"]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
esc = ["normal_mode","collapse_selection", "keep_primary_selection"]
C-a = "select_all"
tab = ["indent"]
S-tab = ["unindent"]

[keys.normal.space]
F = "no_op"
y = "no_op"
Y = "no_op"
p = "no_op"
P = "no_op"
R = "no_op"
h = "no_op"
k = "no_op"
tab = "buffer_picker"
space = "global_search"

[keys.select.space]
F = "no_op"
y = "no_op"
Y = "no_op"
p = "no_op"
P = "no_op"
R = "no_op"
h = "no_op"
k = "no_op"
tab = "buffer_picker"
space = "global_search"

[keys.normal.z]
c = "no_op"
up = "no_op"
down = "no_op"
pageup = "no_op"
pagedown = "no_op"
backspace = "no_op"
space = "no_op"
'/' = "no_op"
'?' = "no_op"
k = "no_op"
j = "no_op"
C-b = "no_op"
C-f = "no_op"
C-u = "no_op"
C-d = "no_op"
n = "no_op"
N = "no_op"


[keys.select.z]
c = "no_op"
up = "no_op"
down = "no_op"
pageup = "no_op"
pagedown = "no_op"
backspace = "no_op"
space = "no_op"
'/' = "no_op"
'?' = "no_op"
k = "no_op"
j = "no_op"
C-b = "no_op"
C-f = "no_op"
C-u = "no_op"
C-d = "no_op"
n = "no_op"
N = "no_op"

[keys.normal.g]
t = "no_op"
c = "no_op"
b = "no_op"
m = "no_op"
y = "no_op"
k = "no_op"
j = "no_op"
'.' = "no_op"

[keys.select.g]
t = "no_op"
c = "no_op"
b = "no_op"
m = "no_op"
y = "no_op"
k = "no_op"
j = "no_op"
'.' = "no_op"

[keys.normal."["]
g = "no_op"
G = "no_op"
c = "no_op"
a = "no_op"
space = "no_op"
"[" = "goto_prev_paragraph"

[keys.normal."]"]
g = "no_op"
G = "no_op"
c = "no_op"
a = "no_op"
space = "no_op"
"]" = "goto_next_paragraph"

[keys.select."["]
g = "no_op"
G = "no_op"
c = "no_op"
a = "no_op"
space = "no_op"
"[" = "goto_prev_paragraph"

[keys.select."]"]
g = "no_op"
G = "no_op"
c = "no_op"
a = "no_op"
space = "no_op"
"]" = "goto_next_paragraph"
