theme = "catppuccin_mocha"

[editor]
true-color = true
auto-info = false
cursorline = true
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "position", "file-encoding"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
y = ":clipboard-yank"
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
y = ":clipboard-yank"
p = ":clipboard-paste-replace"
P = ":clipboard-paste-replace"
