theme = "catppuccin_mocha"

[editor]
true-color = true
cursorline = true
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "position", "file-encoding"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
p = "paste_clipboard_after"
P = "paste_clipboard_before"
esc = ["collapse_selection", "keep_primary_selection"]
V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "delete_selection"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
space = { space = "global_search" }
[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "delete_selection"]
W = ["move_next_long_word_start", "yank_main_selection_to_clipboard", "delete_selection"]
[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
W = ["move_next_long_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]

[keys.select]
y = "yank_main_selection_to_clipboard"
p = "replace_selections_with_clipboard"
P = "paste_clipboard_before"
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
C-i = ["insert_mode", "collapse_selection"]
C-a = ["append_mode", "collapse_selection"]
