theme = "catppuccin_mocha"

[editor]
true-color = true
cursorline = true
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "position", "file-encoding"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
y = ["yank_main_selection_to_clipboard", "collapse_selection"]
d = ["yank_main_selection_to_clipboard", "delete_selection", "collapse_selection"]
p = ["replace_selections_with_clipboard", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "delete_selection"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
space = { space = "global_search" }

[keys.select]
y = ["yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
d = ["yank_main_selection_to_clipboard", "delete_selection", "collapse_selection", "normal_mode"]
p = ["replace_selections_with_clipboard", "collapse_selection", "normal_mode"]
P = ["paste_clipboard_before", "collapse_selection", "normal_mode"]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
C-i = ["insert_mode", "collapse_selection"]
C-a = ["append_mode", "collapse_selection"]
